/*
 ************************************************************************
 * Copyright (C) 2026 Clarivex Technologies Private Limited
 * All Rights Reserved.
 *
 * NOTICE: All intellectual and technical concepts contained
 * herein are proprietary to Clarivex Technologies Private Limited
 * and may be covered by Indian and Foreign Patents,
 * patents in process, and are protected by trade secret or
 * copyright law. Dissemination of this information or reproduction
 * of this material is strictly forbidden unless prior written
 * permission is obtained from Clarivex Technologies Private Limited.
 *
 * Product:   Pervaxis Platform
 * Website:   https://clarivex.tech
 ************************************************************************
 */

using System.IO.Compression;
using LibGit2Sharp;
using Octokit;
using LibGit2SharpRepository = LibGit2Sharp.Repository;
using LibGit2SharpSignature = LibGit2Sharp.Signature;

namespace Pervaxis.Forge.Api.Services;

public sealed class GitHubService : IGitHubService
{
    private readonly Func<string, IGitHubClient> gitHubClientFactory;

    public GitHubService(Func<string, IGitHubClient> gitHubClientFactory)
    {
        this.gitHubClientFactory = gitHubClientFactory;
    }

    public async Task<string> CreateRepositoryAsync(string accessToken, string orgName, string repoName, string description, bool isPrivate, CancellationToken ct = default)
    {
        var client = gitHubClientFactory(accessToken);
        var newRepo = new NewRepository(repoName)
        {
            Description = description,
            Private = isPrivate,
            AutoInit = false
        };

        var repo = await client.Repository.Create(orgName, newRepo);
        return repo.HtmlUrl;
    }

    public async Task ConfigureBranchProtectionAsync(string accessToken, string orgName, string repoName, string branch, CancellationToken ct = default)
    {
        var client = gitHubClientFactory(accessToken);
        var requiredReviews = new BranchProtectionRequiredReviewsUpdate(
            new BranchProtectionRequiredReviewsDismissalRestrictionsUpdate(false),
            dismissStaleReviews: false,
            requireCodeOwnerReviews: false,
            requiredApprovingReviewCount: 1
        );

        var settings = new BranchProtectionSettingsUpdate(
            requiredStatusChecks: null,
            requiredPullRequestReviews: requiredReviews,
            requiredSignatures: false,
            enforceAdmins: false,
            restrictions: null,
            requiredLinearHistory: false,
            allowForcePushes: false,
            allowDeletions: false,
            blockCreations: false,
            requiredConversationResolution: false
        );

        await client.Repository.Branch.UpdateBranchProtection(orgName, repoName, branch, settings);
    }

    public async Task PushInitialCommitAsync(string cloneUrl, string accessToken, byte[] scaffoldZip, string authorName, string authorEmail, CancellationToken ct = default)
    {
        var tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());

        try
        {
            Directory.CreateDirectory(tempDir);
            ZipFile.ExtractToDirectory(new MemoryStream(scaffoldZip), tempDir);

            LibGit2SharpRepository.Init(tempDir);

            using var repo = new LibGit2SharpRepository(tempDir);
            Commands.Stage(repo, "*");

            var signature = new LibGit2SharpSignature(authorName, authorEmail, DateTimeOffset.UtcNow);
            repo.Commit("feat: initial scaffold generated by Pervaxis Forge", signature, signature);

            var remoteUri = cloneUrl.EndsWith(".git") ? cloneUrl : $"{cloneUrl}.git";
            repo.Network.Remotes.Add("origin", remoteUri);

            var options = new PushOptions
            {
                CredentialsProvider = (url, usernameFromUrl, types) =>
                    new UsernamePasswordCredentials
                    {
                        Username = accessToken,
                        Password = string.Empty
                    }
            };

            repo.Network.Push(repo.Branches["main"], options);
        }
        finally
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }
    }
}
