<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Pervaxis.Forge.Engine\Pervaxis.Forge.Engine.csproj" />
    <PackageReference Include="Amazon.AspNetCore.DataProtection.SSM" Version="*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.*" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="*" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.*" />
    <PackageReference Include="AWSSDK.ElastiCache" Version="*" />
    <PackageReference Include="AWSSDK.RDS" Version="*" />
    <PackageReference Include="AWSSDK.S3" Version="*" />
    <PackageReference Include="AWSSDK.SQS" Version="*" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="*" />
    <PackageReference Include="Octokit" Version="*" />
    <PackageReference Include="LibGit2Sharp" Version="*" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="*" />
    <PackageReference Include="Serilog.AspNetCore" Version="*" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="*" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="*" />
    <PackageReference Include="Serilog.Enrichers.Span" Version="*" />
    <PackageReference Include="AWS.Logger.SeriLog" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.15.1-beta.1" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="*" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="*" />
    <PackageReference Include="Asp.Versioning.Http" Version="*" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="BCrypt.Net-Next" Version="*" />
  </ItemGroup>
</Project>
