// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pervaxis.Forge.Api.Data;

#nullable disable

namespace Pervaxis.Forge.Api.Data.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    partial class ForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.DeploymentOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EndpointOrArn")
                        .HasColumnType("text");

                    b.Property<Guid>("GenerationLogId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("GenerationLogId")
                        .HasDatabaseName("idx_deployment_outputs_generation");

                    b.ToTable("deployment_outputs", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.GeneratedService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<JsonDocument>("ManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerticalId", "GeneratedAt")
                        .HasDatabaseName("idx_generated_services_vertical_generated_at");

                    b.HasIndex("VerticalId", "ServiceName")
                        .IsUnique()
                        .HasDatabaseName("idx_generated_services_vertical_name");

                    b.ToTable("generated_services", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.GenerationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("GitHubReposCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("InfrastructureDeployed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<JsonDocument>("Manifest")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("ServiceCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_generation_logs_created_at");

                    b.HasIndex("VerticalId")
                        .HasDatabaseName("idx_generation_logs_vertical");

                    b.ToTable("generation_logs", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.Vertical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ComponentPrefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OwnerTeam")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("idx_verticals_slug");

                    b.ToTable("verticals", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.VerticalCloudConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AwsAccountId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DefaultRegion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("us-east-1");

                    b.Property<string>("IamRoleArn")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("AWS");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerticalId")
                        .IsUnique();

                    b.HasIndex("VerticalId", "Provider")
                        .IsUnique();

                    b.ToTable("vertical_cloud_configs", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.VerticalSourceControlConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("DefaultBranchProtection")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("DefaultVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Private");

                    b.Property<string>("GitHubOrg")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("GitHub");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerticalId")
                        .IsUnique();

                    b.HasIndex("VerticalId", "Platform")
                        .IsUnique();

                    b.ToTable("vertical_source_control_configs", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.VerticalTechDefaults", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DefaultDbEngine")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultEnvironment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("test");

                    b.PrimitiveCollection<string[]>("Environments")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("GenerateCdk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("GenerateTerraform")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("VerticalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerticalId")
                        .IsUnique();

                    b.ToTable("vertical_tech_defaults", (string)null);
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.DeploymentOutput", b =>
                {
                    b.HasOne("Pervaxis.Forge.Api.Data.Entities.GenerationLog", "GenerationLog")
                        .WithMany("DeploymentOutputs")
                        .HasForeignKey("GenerationLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenerationLog");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.GenerationLog", b =>
                {
                    b.HasOne("Pervaxis.Forge.Api.Data.Entities.Vertical", "Vertical")
                        .WithMany("GenerationLogs")
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.GeneratedService", b =>
                {
                    b.HasOne("Pervaxis.Forge.Api.Data.Entities.Vertical", "Vertical")
                        .WithMany("GeneratedServices")
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.VerticalCloudConfig", b =>
                {
                    b.HasOne("Pervaxis.Forge.Api.Data.Entities.Vertical", "Vertical")
                        .WithOne("CloudConfig")
                        .HasForeignKey("Pervaxis.Forge.Api.Data.Entities.VerticalCloudConfig", "VerticalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.VerticalSourceControlConfig", b =>
                {
                    b.HasOne("Pervaxis.Forge.Api.Data.Entities.Vertical", "Vertical")
                        .WithOne("SourceControlConfig")
                        .HasForeignKey("Pervaxis.Forge.Api.Data.Entities.VerticalSourceControlConfig", "VerticalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.VerticalTechDefaults", b =>
                {
                    b.HasOne("Pervaxis.Forge.Api.Data.Entities.Vertical", "Vertical")
                        .WithOne("TechDefaults")
                        .HasForeignKey("Pervaxis.Forge.Api.Data.Entities.VerticalTechDefaults", "VerticalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.GenerationLog", b =>
                {
                    b.Navigation("DeploymentOutputs");
                });

            modelBuilder.Entity("Pervaxis.Forge.Api.Data.Entities.Vertical", b =>
                {
                    b.Navigation("CloudConfig");

                    b.Navigation("GenerationLogs");

                    b.Navigation("GeneratedServices");

                    b.Navigation("SourceControlConfig");

                    b.Navigation("TechDefaults");
                });
#pragma warning restore 612, 618
        }
    }
}
